name: Deploy Backend to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Copy backend to EC2
      run: scp -o StrictHostKeyChecking=no -r ./server/* ec2-user@change this:~/server
    - name: SSH into EC2 and restart server using pm2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@chnage this "source ~/.bashrc && cd ~/server && pm2 reload all"
            