name: backend-ec2-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy backend to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./server/* ec2-user@13.60.80.141:/home/ec2-user/aws-video-collector/server/

      - name: SSH into EC2 and deploy backend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.60.80.141 << 'EOF'
          cd /home/ec2-user/aws-video-collector/server
         