name: Deploy Backend to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Copy backend to EC2
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./server/* ec2-user@54.83.92.115:/home/ec2-user/aws-video-collector/server/
          rm private_key.pem
      
    - name: SSH into EC2 and restart server using pm2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.83.92.115 "source ~/.bashrc && cd ~/aws-video-collector/server && pm2 reload all"
