name: backend-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create remote directory for backend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.60.80.141 "mkdir -p /home/ec2-user/aws-video-collector/server"

      - name: Copy backend to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./server/* ec2-user@13.60.80.141:/home/ec2-user/aws-video-collector/server/
          if [ $? -ne 0 ]; then
            echo "Error: Failed to copy backend files to EC2 instance"
            exit 1
          fi

      - name: SSH into EC2 and deploy backend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.60.80.141 << 'EOF'
            cd /home/ec2-user/aws-video-collector/server
            git pull origin main
            if [ $? -ne 0 ]; then
              echo "Error: Failed to pull latest backend code from Git"
              exit 1
            fi
            sudo systemctl restart backend.service
            if [ $? -ne 0 ]; then
              echo "Error: Failed to restart backend service"
              exit 1
            fi
          EOF
